// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppawbcygxpxfmwvobcdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwYXdiY3lneHB4Zm13dm9iY2RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1MDU5MTEsImV4cCI6MjA3NjA4MTkxMX0.QLxnbduyQkoPQRQ5aQGoce2fLDryWPHPuFFls18F3VY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});